// Static config — URLs/credentials are overridable in Settings
// Service URL map for quick-launch links
export const SERVICE_URLS = {
  'Traefik - Fort':       'http://10.0.5.99:8080',
  'Mantrae':              'https://mantrae.example.com',
  'Authentik':            'https://auth.example.com',
  'Grafana':              'https://grafana.example.com',
  'Portainer - Union':    'https://union.example.com',
  'Portainer - Fort':     'https://fortainer.example.com',
  'Portainer - Pi':       'https://pitainer.example.com',
  'Netdata - Hawk':       'https://stopstats.example.com',
  'LibreNMS':             'https://librenms.example.com',
  'CheckCle':             'https://checkcle.example.com',
  'Holodeck (Jellyfin)':  'https://holodeck.example.com',
  'Retro Gaming':         'https://retro.example.com',
  'Immich':               'https://immich.example.com',
  'OpenCloud':            'https://opencloud.example.com',
  'qBittorrent':          'https://torrent.example.com',
  'n8n':                  'https://automation.example.com',
  'Kasm':                 'https://kasm.example.com',
  'Heimdall (Lab)':       'https://lab.example.com',
  'Chrome Remote':        'https://chrome.example.com',
  'Vault':                'https://vault.example.com',
  'NetBox':               'https://netbox.example.com',
};

// Grafana dashboard shortcuts — paths relative to grafanaUrl in Settings
// Update these to match your actual dashboard UIDs/slugs
export const GRAFANA_DASHBOARDS = [
  { name: 'Infrastructure Overview', icon: 'server-outline',      path: '/d/homelab' },
  { name: 'Network Traffic',         icon: 'analytics-outline',   path: '/d/network' },
  { name: 'System Metrics',          icon: 'speedometer-outline', path: '/d/system' },
  { name: 'All Dashboards',          icon: 'grid-outline',        path: '/dashboards' },
];

export const GROUPS = [
  'Infrastructure',
  'Monitoring',
  'Security',
  'Media',
  'Files & Storage',
  'Automation',
  'Network',
  'Applications',
];

export const SERVICE_GROUPS = {
  'Traefik - Fort':       'Infrastructure',
  'OPNsense - Hawk':      'Infrastructure',
  'OPNsense - Fort':      'Infrastructure',
  'Portainer - Union':    'Infrastructure',
  'Portainer - Fort':     'Infrastructure',
  'Portainer - Pi':       'Infrastructure',
  'Authentik':            'Infrastructure',
  'Mantrae':              'Infrastructure',
  'Grafana':              'Monitoring',
  'Netdata - Hawk':       'Monitoring',
  'Netdata - Fort':       'Monitoring',
  'LibreNMS':             'Monitoring',
  'CheckCle':             'Monitoring',
  'Keycloak':             'Security',
  'Vault':                'Security',
  'Holodeck (Jellyfin)':  'Media',
  'Retro Gaming':         'Media',
  'Spotify Web':          'Media',
  'Immich':               'Files & Storage',
  'OpenCloud':            'Files & Storage',
  'qBittorrent':          'Files & Storage',
  'Prowlarr':             'Files & Storage',
  'n8n':                  'Automation',
  'Kasm':                 'Automation',
  'Chrome Remote':        'Automation',
  'Heimdall (Lab)':       'Automation',
  'NetTools':             'Network',
  'IPAM (phpIPAM)':       'Network',
  'GIS':                  'Network',
  'NetBox':               'Network',
  'Amp Controller 1':     'Applications',
  'Amp Controller 2':     'Applications',
  'Amp Controller 3':     'Applications',
  'Plan':                 'Applications',
  'Everything Search':    'Applications',
  'Weather':              'Applications',
  'Homepage':             'Applications',
  'Routes Dashboard':     'Applications',
};
