// Static config — URLs/credentials are overridable in Settings
// Service URL map for quick-launch links
export const SERVICE_URLS = {
  'Traefik - Hawk':       'http://10.0.11.99:8080',
  'Traefik - Fort':       'http://10.0.18.99:8080',
  'Authentik':            'https://auth.galaxy.rip',
  'Grafana':              'https://grafana.galaxy.rip',
  'Portainer - Containy': 'https://portainer.galaxy.rip',
  'Portainer - Fort':     'https://fortainer.galaxy.rip',
  'Portainer - Pi':       'https://pitainer.galaxy.rip',
  'Netdata - Hawk':       'https://stopstats.galaxy.rip',
  'LibreNMS':             'https://librenms.galaxy.rip',
  'CheckCle':             'https://checkcle.galaxy.rip',
  'Holodeck (Jellyfin)':  'https://holodeck.galaxy.rip',
  'Retro Gaming':         'https://retro.galaxy.rip',
  'Immich':               'https://immich.galaxy.rip',
  'OpenCloud':            'https://opencloud.galaxy.rip',
  'qBittorrent':          'https://torrent.galaxy.rip',
  'n8n':                  'https://automation.galaxy.rip',
  'Kasm':                 'https://kasm.galaxy.rip',
  'Heimdall (Lab)':       'https://lab.galaxy.rip',
  'Chrome Remote':        'https://chrome.galaxy.rip',
  'Vault':                'https://vault.galaxy.rip',
};

export const GROUPS = [
  'Infrastructure',
  'Monitoring',
  'Security',
  'Media',
  'Files & Storage',
  'Automation',
  'Network',
  'Applications',
];

export const SERVICE_GROUPS = {
  'Traefik - Hawk':       'Infrastructure',
  'Traefik - Fort':       'Infrastructure',
  'OPNsense - Hawk':      'Infrastructure',
  'OPNsense - Fort':      'Infrastructure',
  'Portainer - Containy': 'Infrastructure',
  'Portainer - Fort':     'Infrastructure',
  'Portainer - Pi':       'Infrastructure',
  'Authentik':            'Infrastructure',
  'VoidAuth':             'Infrastructure',
  'Mantrae':              'Infrastructure',
  'Grafana':              'Monitoring',
  'Netdata - Hawk':       'Monitoring',
  'Netdata - Fort':       'Monitoring',
  'LibreNMS':             'Monitoring',
  'CheckCle':             'Monitoring',
  'Keycloak':             'Security',
  'Vault':                'Security',
  'Holodeck (Jellyfin)':  'Media',
  'Retro Gaming':         'Media',
  'Spotify Web':          'Media',
  'Immich':               'Files & Storage',
  'OpenCloud':            'Files & Storage',
  'qBittorrent':          'Files & Storage',
  'Prowlarr':             'Files & Storage',
  'n8n':                  'Automation',
  'Kasm':                 'Automation',
  'Chrome Remote':        'Automation',
  'Heimdall (Lab)':       'Automation',
  'NetTools':             'Network',
  'IPAM (phpIPAM)':       'Network',
  'GIS':                  'Network',
  'Amp Controller 1':     'Applications',
  'Amp Controller 2':     'Applications',
  'Amp Controller 3':     'Applications',
  'Plan':                 'Applications',
  'Everything Search':    'Applications',
  'Weather':              'Applications',
  'Homepage':             'Applications',
  'Routes Dashboard':     'Applications',
};
