#!/usr/bin/env bash
# Generates the holodeck monitoring compose (cAdvisor + one mysqld_exporter per
# database) and the Prometheus file_sd targets, from databases.list.
# Re-run any time you add/remove a database.
set -euo pipefail
cd "$(dirname "$0")"

LIST="${1:-databases.list}"
COMPOSE="docker-compose.generated.yml"
TARGETS="prometheus/mysql-targets.generated.json"
HOLO_HOST="${HOLODECK_HOST:-holodeck.fort.galaxy.rip}"
EXPORTER_IMAGE="${MYSQLD_EXPORTER_IMAGE:-prom/mysqld-exporter:v0.15.1}"
CADVISOR_IMAGE="${CADVISOR_IMAGE:-gcr.io/cadvisor/cadvisor:v0.49.1}"
# cAdvisor host port. NOT 8080 — that's AMP's panel port on holodeck. Override
# with CADVISOR_PORT=... if 8081 is also taken. Must match the Prometheus target.
CADVISOR_PORT="${CADVISOR_PORT:-8081}"

[ -f "$LIST" ] || { echo "error: $LIST not found" >&2; exit 1; }
mkdir -p prometheus

trim() { sed 's/^[[:space:]]*//; s/[[:space:]]*$//'; }

cat > "$COMPOSE" <<YAML
# GENERATED by generate.sh from ${LIST} — do not edit by hand.
# Runs on holodeck:  docker compose -f ${COMPOSE} up -d
services:
  cadvisor:
    image: ${CADVISOR_IMAGE}
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    ports:
      - "${CADVISOR_PORT}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
YAML

echo "[" > "$TARGETS"

first=1
count=0
names=""
while IFS= read -r raw || [ -n "$raw" ]; do
  line="${raw%%#*}"
  line="$(printf '%s' "$line" | trim)"
  [ -z "$line" ] && continue

  IFS='|' read -r name addr port <<<"$line"
  name="$(printf '%s' "${name:-}" | trim)"
  addr="$(printf '%s' "${addr:-}" | trim)"
  port="$(printf '%s' "${port:-}" | trim)"
  if [ -z "$name" ] || [ -z "$addr" ] || [ -z "$port" ]; then
    echo "war: skipping malformed line: $raw" >&2; continue
  fi
  slug="$(printf '%s' "$name" | tr '[:upper:] ' '[:lower:]-' | tr -cd 'a-z0-9-')"

  cat >> "$COMPOSE" <<YAML

  mysqld-exporter-${slug}:
    image: ${EXPORTER_IMAGE}
    container_name: mysqld-exporter-${slug}
    restart: unless-stopped
    command:
      - "--mysqld.address=${addr}"
      - "--mysqld.username=\${DB_MON_USER}"
    environment:
      - MYSQLD_EXPORTER_PASSWORD=\${DB_MON_PASS}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${port}:9104"
YAML

  [ $first -eq 0 ] && printf ',\n' >> "$TARGETS"
  first=0
  printf '  { "targets": ["%s:%s"], "labels": { "server": "%s" } }' \
    "$HOLO_HOST" "$port" "$name" >> "$TARGETS"
  names="${names:+$names,}${HOLO_HOST}:${port}=${name}"
  count=$((count + 1))
done < "$LIST"

printf '\n]\n' >> "$TARGETS"

echo "Generated $COMPOSE (cAdvisor + $count exporter(s)) and $TARGETS"
echo
echo "Next:"
echo "  1. On holodeck:      docker compose -f $COMPOSE up -d"
echo "  2. On Prometheus:    add cAdvisor target ${HOLO_HOST}:${CADVISOR_PORT} to the cadvisor job"
echo "                       copy $TARGETS -> /etc/prometheus/holodeck/mysql-targets.json"
echo "                       add prometheus/mysql-job.yml to scrape_configs, then reload"
echo
echo "The 'server' label already names each DB in the app. If you'd rather map"
echo "names in the dashboard instead, add to dashboard/.env:"
echo "  DB_FRIENDLY_NAMES=${names}"
